#!/bin/bash
# For Ubuntu 22.04
First create jenkins Server to execute terraform files from jenkins (t2.medium)
While creating the Jenkins server, we have to create a security group, instance profile and then add the script as user data.

  # Intsalling Java
  sudo apt update -y
  sudo apt install openjdk-17-jre -y
  sudo apt install openjdk-17-jdk -y
  java --version

  # Installing Jenkins
  curl -fsSL https://pkg.jenkins.io/debian/jenkins.io-2023.key | sudo tee \
    /usr/share/keyrings/jenkins-keyring.asc > /dev/null
  echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
    https://pkg.jenkins.io/debian binary/ | sudo tee \
    /etc/apt/sources.list.d/jenkins.list > /dev/null
  sudo apt-get update -y
  sudo apt-get install jenkins -y
  jenkins -v

  # Installing Docker 
  sudo apt update -y
  sudo apt install docker.io -y
  #sudo usermod -aG docker jenkins
  sudo usermod -aG docker ubuntu
  sudo systemctl restart docker
  sudo chmod 777 /var/run/docker.sock

  # If you don't want to install Jenkins, you can create a container of Jenkins
  docker run -d -p 8080:8080 -p 50000:50000 -v jenkins-volume:/var/jenkins_home --name jenkins-container jenkins/jenkins:lts

  # Run Docker Container of Sonarqube
  #!/bin/bash
  docker run -d  --name sonar -p 9000:9000 sonarqube:lts-community


  # Installing AWS CLI
  #!/bin/bash
  curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  sudo apt install unzip -y
  unzip awscliv2.zip
  sudo ./aws/install

  # Installing Kubectl
  #!/bin/bash
  sudo apt update
  sudo apt install curl -y
  sudo curl -LO "https://dl.k8s.io/release/v1.28.4/bin/linux/amd64/kubectl"
  sudo chmod +x kubectl
  sudo mv kubectl /usr/local/bin/
  kubectl version --client


  # Installing eksctl
  #! /bin/bash
  curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
  sudo mv /tmp/eksctl /usr/local/bin
  eksctl version

  # Installing Terraform
  #!/bin/bash
  sudo apt-get update
  apt-get install wget
  sudo apt install -y wget gnupg
  wget -qO- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
  apt update &&  apt install -y software-properties-common
  apt-add-repository "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com ubuntu $(lsb_release -cs) main"
  apt update
  apt install terraform -y

  # Installing Trivy
  #!/bin/bash
  sudo apt-get install wget apt-transport-https gnupg lsb-release -y
  wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
  echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
  sudo apt update
  sudo apt install trivy -y


  # Intalling Helm
  #! /bin/bash
  sudo snap install helm --classic


Using the user data, we have installed all the necessory services.

Jenkins: 008082b9dc294bcebe031e2035b84db0

Install plugins in jenkins:
  1- aws creds
  2- pipeline: aws

Add access keys in jenkins via aws creds

Install terraform plugin in jenkins.
Install terraform inside jenkins container.
apt-get update && apt-get install -y gnupg curl lsb-release
curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com \
$(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
apt-get update
apt-get install terraform


# s3
Create bucket "bucket-for-project-01"